### ISSUE TITLE
Errors, solutions (i) Couldn't open edu.umass.cs.mallet.base.util.MalletLogger; (ii) Logging configuration class "edu.umass.cs.mallet.base.util.Logger.DefaultConfigurator" failed

### ISSUE THREAD

**Issue by victoriastuart** [sistanlp/banner#1]
In case this is useful to anyone, two errors I encountered upon running 'run.sh', and how I resolved them (adjust your paths accordingly; I am currently using Ubuntu 15.04 amd64 and java-1.8.0-openjdk-amd64; following done in gnome-terminal).
#### 1. 'Couldn't open edu.umass.cs.mallet.base.util.MalletLogger resources/logging.properties file.'

Solution:

Copy 'logging.properties' from

src/main/java/edu/umass/cs/mallet/base/util/resources/logging.properties

to

target/scala-2.11/classes/edu/umass/cs/mallet/base/util/resources/logging.properties
#### 2. 'Logging configuration class "edu.umass.cs.mallet.base.util.Logger.DefaultConfigurator" failed'

Based on my Google searches, you can can ignore this error.

[https://osdir.com/ml/ai.mallet.devel/2007-11/msg00008.html](https://osdir.com/ml/ai.mallet.devel/2007-11/msg00008.html) >> "I think this is a bug with the distribution but that it affects logging only. I've always ignored this warning."

[http://comments.gmane.org/gmane.comp.ai.mallet.devel/200](http://comments.gmane.org/gmane.comp.ai.mallet.devel/200)  >>  "This bug should not affect your output."

[http://courses.washington.edu/ling572/winter09/teaching_slides/1_08_Mallet.pptx](http://courses.washington.edu/ling572/winter09/teaching_slides/1_08_Mallet.pptx) >> Slide 20: "Please ignore this message." [Fei Xia, Jan 2009, 'Introduction to Mallet', Andrew McCallum's group at UMass ([https://people.cs.umass.edu/~mccallum/](https://people.cs.umass.edu/~mccallum/))]

**Comment by MihaiSurdeanu** [comment]
Thank you!
Mihai

**Comment by victoriastuart** [comment]
Oct 14, 2015

You are very welcome; thank you for this contribution (repository)!

Victoria  :-)

# 

----- Original Message(s): -----
Date: 2015 Oct 14 (Wed) 17:08
